---
- name: Create Deployment Host Container
  hosts: localhost
  gather_facts: false

  vars:
    control_server: "control-server"

  vars_files:
  - credentials.yml

  tasks:
  - name: Update docker python modules
    pip:
      name: ['docker-py', 'requests']
      state: present

  - name: Log into DockerHub
    docker_login:
      username: "carlosfrias"
      password: "{{ password }}"

  - name: Build Control Server Container
    docker_container:
      name: "{{ control_server }}"
      state: started
      restart: yes
      recreate: yes
      image: ubuntu:18.04
      interactive: yes
      privileged: yes
      tty: yes
      working_dir: "/opt/workstation_setup"
      volumes:
        - "{{ playbook_dir }}:/opt/workstation_setup"
        - "{{ '~/.ssh' | expanduser }}:/root/.ssh"
        - "{{ '~/.ansible' | expanduser }}:/root/.ansible"
      command: ["bash"]


  - name: Prepare Deployment Host
    shell: "{{ item }}"
    with_items:
    - "docker exec {{ control_server }} apt-get update -y"
    - "docker exec {{ control_server }} apt-get dist-upgrade -y"
    - "docker exec {{ control_server }} apt-get install python3-pip openssh-client -y"
    - "docker exec {{ control_server }} pip3 install ansible"
    - "docker exec {{ control_server }} ansible-playbook /opt/workstation_setup/2-prepare-deployment-host.yml"
    - "docker exec {{ control_server }} ansible-playbook /opt/workstation_setup/3-update-with-configured-openstack_user_config.yml"
    - "docker exec {{ control_server }} ansible-playbook /opt/workstation_setup/4-configure-target-hosts.yml"

