---
- name: Prepare Deployment Host
  hosts: localhost
  gather_facts: false
  become: yes

  vars_files:
  - prepare-attributes.yml

  tasks:
  - name: Ansible Bootstrap
    shell: "{{ openstack_src_dir }}/scripts/bootstrap-ansible.sh"

  - name: Set Credentials
    shell: "{{ openstack_src_dir }}/scripts/pw-token-gen.py --file {{ openstack_src_dir }}{{ deployment_dest_dir }}/user_secrets.yml"
