---
- name: Initial workstation setup
  hosts: localhost
  gather_facts: false
  vars: 
    os_packages:
    - htop
    - mc
    - tmux

  tasks: 
    - name: Install OS packages
      become: true
      package: 
        name: "{{ item }}"
        state: present 
      with_items: "{{ os_packages }}"

