---
- name: Initial workstation setup
  hosts: localhost
  gather_facts: true
  vars: 
    os_packages:
    - htop
    - mc
    - tmux

  tasks: 
    - name: Update by distribution
      become: true
      apt: 
        name: "{{ item }}"
        state: present
      with_items: 
        - python-apt
      when: ansible_distribution == "Ubuntu"

    - name: Install OS packages
      become: true
      package: 
        name: "{{ item }}"
        state: present 
      with_items: "{{ os_packages }}"

