---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu1604
    image: geerlingguy/docker-ubuntu1604-ansible
    pre_build_image: true
  - name: centos7
    image: geerlingguy/docker-centos7-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible