---
- name: Docker build tutorial
  hosts: localhost
  connection: local

  tasks:
  - name: Ensure Docker image is build from the test Dockerfile
    tags: ['build']
    docker_image:
      name: test
      source: build
      build:
        path: test
      state: present

  - name: Ensure the test container is running
    tags: ['start']
    docker_container:
      image: test:latest
      name: test
      state: started

