---
# tasks file for ssh_lockdown_login
- name: Lock down root and password login over SSH
  become: yes
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '{{ item }}'
    line: '\2 no'
    backrefs: yes
  when: permit_root_login | default(False)
  with_items:
    - "(#)(PasswordAuthentication)(.*)"
    - "(#)(PermitRootLogin)(.*)"
  notify:
    - Restart SSH service