---
# tasks file for /usr/local/google/home/friasc/apigee-workspace/apigee-opdk-role-workspace/apigee-opdk-admin-user
- name: Assert ansible user is provided
  assert:
    that:
    - ansible_user is defined
    - ansible_user | trim | length > 0
    fail_msg: "Please provide the name of the '-e ansible_user=<ssh user name>'"

- name: Copy local public keys to server for user.
  become: yes
  authorized_key:
    user: '{{ ansible_user }}'
    state: present
    key: "{{ lookup('file', '{{ pubkey_path }}') }}"
  when: pubkey_path is defined | default(False)

- name: Update user with NOPASSWD.
  become: yes
  lineinfile:
    state: present
    create: yes
    mode: 0440
    line: "{{ item }}"
    path: "/etc/sudoers"
    validate: '/usr/sbin/visudo -cf %s'
  with_items:
    - "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
